modLoader = "javafml"
loaderVersion = "${loader_version_range}"
issueTrackerURL = "${mod_issue_tracker}"
license = "${mod_license}"

[[mixins]]
    config = "werewolves.mixins.json"


[[mods]]
    modId = "${mod_id}"
    namespace = "werewolves"
    version = "${mod_version}"
    displayName = "${mod_name}"
    displayURL = "${mod_url}"
    logoFile = "logo.png"
    credits = "RebelT (models/textures), Maxanier (vampirism), 1LiterZinalco (models) Йода (textures), CritterCarnival (textures), Talonerd (textures), https://freesound.org (sounds), Mike (testing/ideas), LilCatGod (testing/ideas)"
    authors = "${mod_authors}"
    description = '''${mod_description}'''
    updateJSONURL = "https://api.modrinth.com/updates/werewolves/forge_updates.json"
    enumExtensions="META-INF/enumextensions.json"
[[dependencies.${ mod_id }]]
    modId = "neoforge"
    type = "required"
    versionRange = "${forge_version_range}"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.${ mod_id }]]
    modId = "vampirism"
    type = "required"
    versionRange = "${vampirism_version_range}"
    ordering = "BEFORE"
    side = "BOTH"