name: Test Crowdin 

on:
  workflow_dispatch:
  push:
    branches:
      - '1.[0-9]+'
      - '1.[0-9]+.[0-9]+'
    paths:
      - 'src/main/resources/assets/werewolves/lang/en_us.json'

jobs:
  upload-translations:
    environment: Testing
    runs-on: ubuntu-latest

    steps:
      - name: get crowdin branch
        id: get_crowdin_branch
        run: |
          echo ::set-output name=crowdin_branch::$(echo ${{ github.ref_name }} | cut -d '.' -f 1,2)
      - uses: actions/checkout@v3
      - name: Upload translations
        uses: crowdin/github-action@v1
        with:
          branch: ${{ steps.get_crowdin_branch.outputs.crowdin_branch }}
        env:
          CROWDIN_KEY: ${{ secrets.CROWDIN_KEY }}
