name: Publish Beta

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Indicator'
        default: '1'
        required: true
        type: string

permissions:
  contents: read

jobs:
  publish-beta:
    environment: Testing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'
      - name: Download translations
        uses: crowdin/github-action@v1
        with:
          download_translations: true
          upload_sources: false
        env:
          CROWDIN_KEY: ${{ secrets.CROWDIN_KEY }}
      - name: Publish
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: build publish curseforge modrinth -PMAVEN_URL=${{ secrets.MAVEN_URL }} -PMAVEN_USER=${{ secrets.MAVEN_USER }} -PMAVEN_TOKEN=${{ secrets.MAVEN_TOKEN }} -PCURSEFORGE_API=${{ secrets.CURSEFORGE_API }} -PMODRINTH_API=${{ secrets.MODRINTH_API }} -Pbeta=${{ github.event.inputs.version }}